document.querySelector('#world-upgrade-list').addEventListener('pointerdown',e=>{let id=e.target.dataset.upgrade;if(!id)return;let u=upgrades.find(x=>x.id===id),level=upgradeLevel(id),cost=level<u.max?upgradeCost(u,level):Infinity;if(save.credits>=cost){save.credits-=cost;currentUpgradeLevels()[id]++;localStorage.setItem('deep-driller-save',JSON.stringify(save));toast(u.name.toUpperCase()+' AMELIORE');updateUI()}});
document.querySelector('#world-upgrade-list').addEventListener('click',e=>{let id=e.target.dataset.upgrade;if(!id)return;let u=upgrades.find(x=>x.id===id),level=upgradeLevel(id),cost=level<u.max?upgradeCost(u,level):Infinity;if(save.credits>=cost){save.credits-=cost;currentUpgradeLevels()[id]++;localStorage.setItem('deep-driller-save',JSON.stringify(save));toast(u.name.toUpperCase()+' AMELIORE');updateUI()}});
function syncWorkbenchPanel(){const panel=document.querySelector('.right-panel'),worldPanel=document.querySelector('#world-workbench-panel'),frame=document.querySelector('.canvas-frame'),isMobile=window.matchMedia('(max-width:900px)').matches,atWorkbench=state&&state.x===WORKBENCH_X&&state.y===WORKBENCH_Y&&!isMobile;if(atWorkbench){const firstOpen=!worldPanel.classList.contains('show'),frameRect=frame.getBoundingClientRect(),canvasRect=canvas.getBoundingClientRect(),scaleX=canvasRect.width/canvas.width,scaleY=canvasRect.height/canvas.height,workbenchX=canvasRect.left-frameRect.left+(WORKBENCH_X-cameraX)*TILE_PX*scaleX+TILE_PX*scaleX/2,workbenchY=canvasRect.top-frameRect.top+(WORKBENCH_Y-cameraY)*TILE_PX*scaleY;worldPanel.classList.add('show');worldPanel.style.left=Math.max(worldPanel.offsetWidth/2+8,Math.min(frameRect.width-worldPanel.offsetWidth/2-8,workbenchX))+'px';worldPanel.style.top=Math.max(8,workbenchY-worldPanel.offsetHeight-12)+'px';panel.classList.add('workbench-world');if(firstOpen)toast('ETABLI : AMELIORATIONS DISPONIBLES')}else{worldPanel.classList.remove('show');panel.classList.remove('workbench-world')}setTimeout(syncWorkbenchPanel,120)}
setTimeout(syncWorkbenchPanel,120);
function drawWorkbench(){const tileCameraX=Math.floor(cameraX),tileCameraY=Math.floor(cameraY),offsetX=Math.round((cameraX-tileCameraX)*TILE_PX),offsetY=Math.round((cameraY-tileCameraY)*TILE_PX),worldX=nearestWorldX(WORKBENCH_X),drawX=(worldX-tileCameraX)*TILE_PX-offsetX,drawY=(WORKBENCH_Y-tileCameraY)*TILE_PX-offsetY;if(tiles.complete)ctx.drawImage(tiles,48,16,ASSET_TILE,ASSET_TILE,drawX,drawY,TILE_PX,TILE_PX)}
const canvas = document.querySelector('#game-canvas');
const ctx = canvas.getContext('2d');
ctx.imageSmoothingEnabled = false;
ctx.imageSmoothingQuality = 'low';
const character = new Image(); character.src = 'character.png';
const tiles = new Image(); tiles.src = 'tileset.png?v=platforms-1';
const backgroundTexture = new Image(); backgroundTexture.src = 'background.png';
const foregroundTexture = new Image(); foregroundTexture.src = 'foreground.png';
let spawnSoundData=null,walkSoundData=null,hitSoundData=null,fallSoundData=null,spawnSoundPending=false,audioContext=null;
function playSound(soundData){if(!soundData)return;const AudioCtor=window.AudioContext||window.webkitAudioContext;if(!AudioCtor)return;if(!audioContext)audioContext=new AudioCtor();if(audioContext.state==='suspended'){spawnSoundPending=true;audioContext.resume().then(()=>{if(spawnSoundPending){spawnSoundPending=false;playSound(soundData)}}).catch(()=>{});return}const now=audioContext.currentTime;const duration=Math.min(1.2,Math.max(.12,(soundData.p_env_sustain||0)+(soundData.p_env_decay||0)));const volume=Math.min(.24,Math.max(.03,soundData.sound_vol||.1));const sampleRate=audioContext.sampleRate||44100;const buffer=audioContext.createBuffer(1,Math.max(1,Math.floor(sampleRate*duration)),sampleRate);const data=buffer.getChannelData(0);let previous=0;for(let i=0;i<data.length;i++){const time=i/sampleRate;const white=(Math.random()*2-1);const brown=(previous+0.02*white)/1.02;previous=brown;const lowPass=0.4+Math.min(0.9,(soundData.p_lpf_freq||0.08)*2.5);const highPass=0.12+Math.min(0.8,(soundData.p_hpf_freq||0.18)*2.2);const envelope=Math.max(0,1-time/duration);const attackCurve=Math.min(1,Math.max(0,time/(duration*0.08||0.02)));const punch=1+(soundData.p_env_punch||0)*2.2;const noise=((white*0.7)+(brown*0.3))*Math.max(0,1-highPass)*lowPass;data[i]=noise*envelope*attackCurve*punch*volume;}const source=audioContext.createBufferSource();source.buffer=buffer;const filter=audioContext.createBiquadFilter();filter.type='lowpass';filter.frequency.setValueAtTime(1200+((soundData.p_lpf_freq||0.08)*7000),now);const gain=audioContext.createGain();gain.gain.setValueAtTime(0.0001,now);gain.gain.linearRampToValueAtTime(volume,now+Math.min(.02,duration*.15));gain.gain.exponentialRampToValueAtTime(0.0001,now+duration);source.connect(filter).connect(gain).connect(audioContext.destination);source.start(now);source.stop(now+duration+0.05)}
function playSpawnSound(){playSound(spawnSoundData)}
function playWalkSound(){playSound(walkSoundData)}
function playHitSound(){playSound(hitSoundData)}
function playFallSound(){playSound(fallSoundData)}
function loadSounds(){Promise.all(['spawn-sound.json','walk-sound.json','hit-sound.json','fall-sound.json'].map(file=>fetch(file).then(response=>response.json()))).then(([spawn,walk,hit,fall])=>{spawnSoundData=spawn;walkSoundData=walk;hitSoundData=hit;fallSoundData=fall;playSpawnSound()}).catch(()=>{})}
const TILE = 8, ASSET_TILE = 8, VIEW_COLS = 12, W = 80, H = 64;
const CHEST_X = 38, CHEST_Y = 3;
const WORKBENCH_X = CHEST_X + 2, WORKBENCH_Y = CHEST_Y;
const SURFACE_Y = 4, ACCESS_START_X = CHEST_X - 4, ACCESS_WIDTH = 3;
const PLATFORM_TILE = 6;
const MAP_LEFT = 1, MAP_RIGHT = W - 2;
let TILE_PX = 32;
let viewRows = 8, viewCols = 12, cameraX = 0, cameraY = 0, cameraReady = false;
const planets = [
  {name:'TERRA-8', sub:'FRONTIER SOIL', objective:'Extraire 180₡ de minerais', goal:180, base:'#5d4634', rock:'#92704a', accent:'#78cfb2', skyTop:'#050b22', skyBottom:'#245078', orb:'terra-orb', ores:[['cuivre','Cuivre',8,'#c8794b'],['fer','Fer',12,'#9ea7a2'],['quartz','Quartz',25,'#b6e8da']], next:'Fabriquer le module de saut spatial.'},
  {name:'MAGMA-X', sub:'CORE TEMPERATURE', objective:'Atteindre 900₡ et extraire des noyaux', goal:900, base:'#33282c', rock:'#6f3e3c', accent:'#ef7651', skyTop:'#210b18', skyBottom:'#783b36', orb:'magma-orb', ores:[['pyrite','Pyrite',45,'#dcac46'],['rubis','Rubis',90,'#e95d5d'],['core','Core-Lava',180,'#ff9d4d']], next:'Le carburant stellaire est prêt.'},
  {name:'CRYO-0', sub:'FROZEN FRONTIER', objective:'Extraire 3600₡ de cristaux', goal:3600, base:'#22394a', rock:'#537d94', accent:'#7cdded', skyTop:'#061a32', skyBottom:'#3d8da1', orb:'cryo-orb', ores:[['titanium','Titanium',120,'#a7c8ce'],['diamant','Diamant eau',240,'#8cecff'],['helium','Hélium-3',480,'#d8f4ff']], next:'Bouclier thermique assemblé.'},
  {name:'VOID-PRIME', sub:'INFINITE DARK', objective:'Extraire 14000₡ de matière noire', goal:14000, base:'#29203b', rock:'#593d76', accent:'#e78dfc', skyTop:'#09051e', skyBottom:'#4d2f77', orb:'void-orb', ores:[['obsidienne','Obsidienne',300,'#8e74b6'],['matiere','Matière noire',700,'#e78dfc']], next:'MODE INFINI DÉBLOQUÉ.'}
];
let save = JSON.parse(localStorage.getItem('deep-driller-save') || 'null') || {credits:0, planet:0, best:0, upgrades:{drill:0,tank:0,heat:0,cargo:0,collector:0,teleport:0}};
const defaultUpgradeLevels={drill:0,tank:0,heat:0,cargo:0,collector:0,teleport:0};
save.upgrades=Object.assign({},defaultUpgradeLevels,save.upgrades||{});
if(!Array.isArray(save.planetUpgrades)){save.planetUpgrades=Array.from({length:planets.length},()=>Object.assign({},defaultUpgradeLevels));save.planetUpgrades[save.planet]=Object.assign({},save.upgrades)}
function currentUpgradeLevels(){return save.planetUpgrades[save.planet]}
function upgradeLevel(id){return currentUpgradeLevels()[id]||0}
let state, keys = {}, last = 0, terrain = [], durability = [], tileHits = [], particles = [], toastTimer;
const upgrades = [{id:'drill',name:'Tête de forage',desc:'dégâts +',cost:[80,260,900,3200,12000],max:5},{id:'tank',name:'Réservoir / batterie',desc:'autonomie +',cost:[100,340,1200,4200,16000],max:5},{id:'heat',name:'Résistance thermique',desc:'chaleur -',cost:[120,400,1400,5000,19000],max:5},{id:'cargo',name:'Soute blindée',desc:'capacité +',cost:[90,300,1050,3800,14000],max:5},{id:'collector',name:'Bras collecteur',desc:'ramassage +',cost:[200,700,2500,9000,34000],max:5},{id:'teleport',name:'Téléporteur urgence',desc:'retour +',cost:[160,560,2000,7200,27000],max:5}];
save.planetUpgrades.forEach(levels=>upgrades.forEach(upgrade=>{levels[upgrade.id]=Math.min(upgrade.max,Math.max(0,levels[upgrade.id]||0))}));
function upgradeCost(upgrade,level){return Math.round(upgrade.cost[level]*(1+save.planet*2.5))}
function tileDurability(cell,y){if(!cell||cell===PLATFORM_TILE||cell===5)return 0;const depthTier=Math.floor(Math.max(0,y-SURFACE_Y)/12),planetTier=save.planet,planetResistance=3+planetTier*13;return planetResistance+depthTier*3+(cell===3?3:cell===4?7:0)}
function drillDamage(){const level=upgradeLevel('drill'),base=tileDurability(2,4);return level>=5?base:Math.max(1,Math.ceil(base*level/5))}
function newRun(){const p=planets[save.planet]; state={x:Math.floor(W/2),y:3,visualX:Math.floor(W/2),visualY:3,visualFromX:Math.floor(W/2),visualFromY:3,visualTargetX:Math.floor(W/2),visualTargetY:3,visualProgress:1,visualDuration:130,falling:false,fallSoundPlayed:false,jump:null,rotation:0,facing:1,depth:0,value:0,cargoValue:0,progress:0,cargo:[],battery:100,fuel:100,heat:10,combo:1,boost:0,moveCooldown:0,jumpLatched:false,runStart:Date.now(),event:'Le sol est calme. Descends pour trouver du quartz.',ended:false}; terrain=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>y<4?0:2)); generateTerrain(p); durability=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>tileDurability(terrain[y][x],y))); tileHits=[]; updateUI()}
function rand(n){let x=Math.sin(n*999+save.planet*77)*43758.5453;return x-Math.floor(x)}
const STONE_TRANSITION_START=14,STONE_TRANSITION_END=22;
function terrainTexture(x,y){const stoneMix=Math.max(0,Math.min(1,(y-STONE_TRANSITION_START)/(STONE_TRANSITION_END-STONE_TRANSITION_START)));if(rand(x+y*W+431)<stoneMix)return [((wrapX(x)+y)%2)*8,24+((wrapX(x)*3+y)%2)*8];return [((wrapX(x)+y)%2)*8,((wrapX(x)*3+y)%2)*8]}
function generateTerrain(p){terrain=terrain.map(row=>new Proxy(row,{get(target,key){if(typeof key==='string'&&/^-?\d+$/.test(key))return target[wrapX(Number(key))];return Reflect.get(target,key)},set(target,key,value){if(typeof key==='string'&&/^-?\d+$/.test(key)){target[wrapX(Number(key))]=value;return true}return Reflect.set(target,key,value)}}));for(let y=4;y<H;y++)for(let x=1;x<W-1;x++){let r=rand(x+y*W);terrain[y][x]=r<.09?3:r<.18?4:2}for(let x=1;x<W-1;x++)terrain[SURFACE_Y][x]=x>=ACCESS_START_X&&x<ACCESS_START_X+ACCESS_WIDTH?PLATFORM_TILE:5}
function mineAt(x,y){const wrappedX=wrapX(x),cell=terrain[y]?.[wrappedX];if(!cell||cell===5||cell===PLATFORM_TILE)return false;if(cell===1)return true;if(state.cargo.length>=capacity()){state.event='Soute pleine : remonte vendre ta cargaison.';return false}const damage=drillDamage();durability[y][wrappedX]=Math.max(0,durability[y][wrappedX]-damage);tileHits=tileHits.filter(hit=>hit.x!==wrappedX||hit.y!==y);tileHits.push({x:wrappedX,y,elapsed:0,duration:220,flash:true});playHitSound();if(durability[y][wrappedX]>0)return false;const p=planets[save.planet],depthFactor=y/H;let chance=rand(Date.now()+x+y*20);let ore=p.ores[Math.min(p.ores.length-1,Math.floor(chance*p.ores.length))];let val=(cell===2?1:3+Math.floor(rand(Date.now()+x*17+y*31)*3))*((save.planet+1)**2);state.cargo.push({id:ore[0],name:ore[1],value:val,color:ore[3]});state.value+=val;state.cargoValue+=val;state.progress+=val;state.combo=Math.min(9,state.combo+0.25);state.heat+=2+depthFactor*4;terrain[y][wrappedX]=0;if(cell===3){state.event='POCHE DE GAZ : vitesse accrue, mais attention à l’explosion.';state.boost=150;state.heat+=12}if(cell===4){state.event='GEODE RARE : un minerai précieux vient d’être découvert.';state.heat-=5}return true}
function capacity(){const cargoLevel=upgradeLevel('cargo'),collectorLevel=upgradeLevel('collector');return 12+cargoLevel*12+cargoLevel*cargoLevel*3+collectorLevel*18+collectorLevel*collectorLevel*4}
function wrapX(x){return ((Math.round(x)-MAP_LEFT)% (MAP_RIGHT-MAP_LEFT+1)+(MAP_RIGHT-MAP_LEFT+1))%(MAP_RIGHT-MAP_LEFT+1)+MAP_LEFT}
function tileAt(x,y){return terrain[y]?.[wrapX(x)]}
function nearestWorldX(x){return x+Math.round((cameraX-x)/(MAP_RIGHT-MAP_LEFT+1))*(MAP_RIGHT-MAP_LEFT+1)}
function isSolid(x,y){return tileAt(x,y)>1}
const GROUND={0:[0,1],90:[-1,0],'-90':[1,0],180:[0,-1]};
const TANGENT={0:[1,0],90:[0,1],'-90':[0,-1],180:[-1,0]};
const INVERT_ROTATION={0:180,180:0,90:-90,'-90':90};
function clampY(y){return Math.max(3,Math.min(H-2,Math.round(y)))}
function supportOnFace(x,y,rotation){const off=GROUND[rotation],tx=wrapX(x+off[0]),ty=y+off[1],cell=tileAt(tx,ty);if(rotation===0)return cell===PLATFORM_TILE||isSolid(tx,ty);return isSolid(tx,ty)&&cell!==PLATFORM_TILE}
function supportAt(x,y){for(const rotation of[0,90,-90,180])if(supportOnFace(x,y,rotation))return rotation;return null}
function cornerSupportRotation(x,y,dx,dy){if(dx&&dy){const preferredOffset=state.rotation===0||state.rotation===180?[-dx,0]:[0,-dy];const preferred=Object.entries(GROUND).find(([,offset])=>offset[0]===preferredOffset[0]&&offset[1]===preferredOffset[1])?.[0];if(preferred!==undefined&&supportOnFace(x,y,Number(preferred)))return Number(preferred)}return supportAt(x,y)}
function nextSupportRotation(x,y,dx,dy){const preferred=dy>0?[0]:dy<0?[180]:dx>0?[-90]:[90],candidates=[...preferred,state.rotation,0,90,-90,180];return candidates.find(rotation=>supportOnFace(x,y,rotation))??null}
function faceFromDirection(dx,dy,rotation=state.rotation){const radians=rotation*Math.PI/180,dot=dx*Math.cos(radians)+dy*Math.sin(radians);if(dot)state.facing=dot>0?1:-1}
function moveToSupport(tx,ty,worldDx,worldDy,nextRotation){if(nextRotation===null)return false;const worldWidth=MAP_RIGHT-MAP_LEFT+1;state.visualFromX=state.visualX;state.visualFromY=state.visualY;state.x=tx;state.y=ty;state.visualTargetX=tx+Math.round((state.visualX-tx)/worldWidth)*worldWidth;state.visualTargetY=ty;state.visualProgress=0;state.rotation=nextRotation;faceFromDirection(worldDx,worldDy,state.rotation);state.depth=Math.max(state.depth,Math.floor((state.y-3)*3));state.battery-=.45/(1+upgradeLevel('tank')*.22);state.fuel-=.18/(1+upgradeLevel('tank')*.18);if(tx===CHEST_X&&ty===CHEST_Y)depositCargo();return true}
function fallDuration(distance){return Math.max(70,Math.round(100*Math.sqrt(Math.max(1,Math.abs(distance)))))}
function fallFrom(tx,ty){let landingY=ty;while(landingY<H-2){const below=tileAt(tx,landingY+1);if(below&&below!==PLATFORM_TILE)break;landingY++}if(landingY===ty)return false;state.visualFromX=state.visualX;state.visualFromY=state.visualY;state.x=tx;state.y=landingY;state.visualTargetX=state.visualX;state.visualTargetY=landingY;state.visualProgress=0;state.rotation=0;state.falling=true;if(!state.fallSoundPlayed){playFallSound();state.fallSoundPlayed=true;}state.visualDuration=fallDuration(landingY-ty);return true}
function resolveAirborne(){if(supportOnFace(state.x,state.y,state.rotation))return true;const groundedRotation=supportAt(state.x,state.y);if(groundedRotation!==null){state.rotation=groundedRotation;return true}return fallFrom(state.x,state.y)}
// Le personnage reste toujours accroché à une surface (état state.rotation = côté où se trouve la matière).
// Gauche/Droite = roulement tangentiel le long de cette surface, en suivant les bosses (creux) et arêtes (sorties) de la forme.
function crawlHorizontal(dir){const[tdx,tdy]=TANGENT[state.rotation],worldDx=tdx*dir,worldDy=tdy*dir,tx=wrapX(state.x+worldDx),ty=Math.max(0,Math.min(H-2,state.y+worldDy)),cell=tileAt(tx,ty);faceFromDirection(worldDx,worldDy);const cornerSupport=GROUND[state.rotation],cornerDx=worldDx+cornerSupport[0],cornerDy=worldDy+cornerSupport[1],cornerX=wrapX(state.x+cornerDx),cornerY=Math.max(0,Math.min(H-2,state.y+cornerDy)),cornerCell=tileAt(cornerX,cornerY),cornerRotation=cornerSupportRotation(cornerX,cornerY,cornerDx,cornerDy),platformIsPassable=cornerCell===PLATFORM_TILE&&state.rotation!==0;if((!cornerCell||platformIsPassable)&&cornerRotation!==null&&moveToSupport(cornerX,cornerY,cornerDx,cornerDy,cornerRotation)){playWalkSound();return}if(cell&&cell!==PLATFORM_TILE){const wallRotation=Object.entries(GROUND).find(([,offset])=>offset[0]===worldDx&&offset[1]===worldDy)?.[0];if(wallRotation!==undefined&&supportOnFace(state.x,state.y,wallRotation)){state.rotation=Number(wallRotation);state.moveCooldown=0;return}state.moveCooldown=0;return}if(state.rotation===0&&moveToSupport(tx,ty,worldDx,worldDy,state.rotation)){playWalkSound();resolveAirborne();return}if(moveToSupport(tx,ty,worldDx,worldDy,state.rotation)){playWalkSound();resolveAirborne();return}state.moveCooldown=0}
function dropThroughPlatform(tx,ty){let landingY=ty;while(landingY<H-2){const below=tileAt(tx,landingY+1);if(below&&below!==PLATFORM_TILE)break;landingY++}const landingRotation=supportOnFace(tx,landingY,0)?0:null,fallDistance=landingY-state.y;if(landingRotation===null||!moveToSupport(tx,landingY,0,landingY-state.y,landingRotation))return false;state.falling=true;if(!state.fallSoundPlayed){playFallSound();state.fallSoundPlayed=true;}state.visualDuration=fallDuration(fallDistance);return true}
// Bas = forer directement dans la matière à laquelle le personnage est accroché.
function digForward(){const off=GROUND[state.rotation],tx=wrapX(state.x+off[0]),ty=clampY(state.y+off[1]),cell=tileAt(tx,ty);if(!cell)return;faceFromDirection(off[0],off[1]);if(state.rotation===0&&cell===PLATFORM_TILE){if(dropThroughPlatform(tx,ty))return;state.moveCooldown=0;return}if(cell!==PLATFORM_TILE&&!mineAt(tx,ty)){state.moveCooldown=0;return}const nextRotation=nextSupportRotation(tx,ty,off[0],off[1])??state.rotation;if(!moveToSupport(tx,ty,off[0],off[1],nextRotation))state.moveCooldown=0}
// Haut = tentative de saut vers l'extérieur pour attraper une paroi en face ; échec = on reste accroché, sans tomber.
function attemptJump(){if(state.jump||state.ended)return;const off=GROUND[state.rotation],outward=[-off[0],-off[1]];let px=state.x,py=state.y,landingX=null,landingY=null;for(let step=1;step<=5;step++){const nx=wrapX(px+outward[0]),ny=clampY(py+outward[1]),cell=tileAt(nx,ny);if(cell&&cell!==PLATFORM_TILE){landingX=px;landingY=py;break}px=nx;py=ny}if(landingX===null){state.event='SAUT : rien à agripper, tu restes accroché à la paroi.';return}const worldWidth=MAP_RIGHT-MAP_LEFT+1,rawWorldDx=landingX-state.x,worldDx=rawWorldDx-Math.round(rawWorldDx/worldWidth)*worldWidth,worldDy=landingY-state.y,visualTargetX=landingX+Math.round((state.visualX-landingX)/worldWidth)*worldWidth;state.jump={fromX:state.visualX,fromY:state.visualY,toX:visualTargetX,toY:landingY,elapsed:0,duration:170,landX:landingX,landY:landingY,rotation:INVERT_ROTATION[state.rotation]};faceFromDirection(outward[0],outward[1]);state.event='SAUT : tentative d’accroche sur la paroi opposée.'}
function updateJump(dt){const jump=state.jump;if(!jump)return;jump.elapsed+=dt;const t=Math.min(1,jump.elapsed/jump.duration),eased=1-Math.pow(1-t,2);state.visualX=jump.fromX+(jump.toX-jump.fromX)*eased;state.visualY=jump.fromY+(jump.toY-jump.fromY)*eased;if(t>=1){state.x=jump.landX;state.y=jump.landY;state.rotation=jump.rotation;state.visualX=jump.toX;state.visualY=jump.toY;state.visualFromX=jump.toX;state.visualFromY=jump.toY;state.visualTargetX=jump.toX;state.visualProgress=1;state.jump=null;state.moveCooldown=160;state.depth=Math.max(state.depth,Math.floor((state.y-3)*3));if(state.x===CHEST_X&&state.y===CHEST_Y)depositCargo()}}
function update(dt){if(state.ended)return;let boost=keys[' ']||keys.Space;state.moveCooldown-=dt;tileHits=tileHits.filter(hit=>{hit.elapsed+=dt;return hit.elapsed<hit.duration});if(state.jump)updateJump(dt);else if(!state.falling){if(keys.ArrowUp){if(!state.jumpLatched){attemptJump();state.jumpLatched=true}}else state.jumpLatched=false;if(!state.jump&&state.moveCooldown<=0){const dir=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0);if(dir){crawlHorizontal(dir);state.moveCooldown=240/(1+upgradeLevel('drill')*.1)}else if(keys.ArrowDown){digForward();state.moveCooldown=300/(1+upgradeLevel('drill')*.1)}}}if(!state.jump){state.visualProgress=Math.min(1,state.visualProgress+dt/state.visualDuration);const fallProgress=state.falling?state.visualProgress*state.visualProgress:state.visualProgress;state.visualX=state.visualFromX+(state.visualTargetX-state.visualFromX)*fallProgress;state.visualY=state.visualFromY+(state.visualTargetY-state.visualFromY)*fallProgress;if(state.visualProgress>=1){state.visualX=state.visualTargetX;state.visualY=state.visualTargetY;if(state.falling){state.falling=false;state.fallSoundPlayed=false;state.visualDuration=130}}}if(boost&&!state.falling){state.battery-=dt*.001;state.heat+=dt*.004}if(state.y<=SURFACE_Y&&!state.falling&&!state.jump)state.battery=Math.min(100,state.battery+dt*.002);state.boost=Math.max(0,state.boost-dt);state.heat-=dt*.002/(1+upgradeLevel('heat')*.2);if(state.heat>100||state.battery<=0||state.fuel<=0)state.event='SYSTEMS CRITIQUES — RETOURNE AU COFFRE POUR RECHARGER';if(state.depth>34&&save.planet===3)state.event='SIGNAL STELLAIRE : le filtre est proche.';updateUI()}
function depositCargo(){if(!state.cargo.length)return;let score=Math.round(state.cargoValue*(1+state.depth/100)*state.combo);save.credits+=score;save.best=Math.max(save.best,score);localStorage.setItem('deep-driller-save',JSON.stringify(save));state.cargo=[];state.cargoValue=0;state.combo=1;state.event='COFFRE : cargaison déposée au camp de surface.';toast('CARGAISON DÉPOSÉE — +'+score+'₡');if(state.progress>=planets[save.planet].goal){if(save.planet<planets.length-1){save.planet++;localStorage.setItem('deep-driller-save',JSON.stringify(save));toast('PLANÈTE SUIVANTE DÉBLOQUÉE');newRun();return}state.event='OBJECTIF VALIDÉ — LA PLANÈTE RESTE EXPLORABLE'}updateUI()}
function returnBase(emergency=false){if(state.ended)return;depositCargo();state.jump=null;state.x=CHEST_X;state.y=CHEST_Y;state.visualX=CHEST_X;state.visualY=CHEST_Y;state.visualFromX=CHEST_X;state.visualFromY=CHEST_Y;state.visualTargetX=CHEST_X;state.visualTargetY=CHEST_Y;state.visualProgress=1;state.depth=0;state.battery=100;state.fuel=100;state.heat=10;state.fallSoundPlayed=false;state.event=emergency?'RAPATRIEMENT : systèmes réinitialisés au coffre.':'RETOUR AU COFFRE : la planète est conservée.';cameraReady=false;updateUI()}
function aimFrame(){if(state.jump||supportAt(state.x,state.y)!==state.rotation)return null;if(keys.ArrowUp)return 3;if(keys.ArrowDown)return 2;return null}
function characterFrame(){if(state.falling)return 4;const aimedFrame=aimFrame();return aimedFrame===null?Math.floor((Date.now()/280)%2):aimedFrame}
function drawBackground(){if(!backgroundTexture.complete)return;const chunkSize=TILE_PX*4,parallaxX=cameraX*.22*TILE_PX,parallaxY=cameraY*.18*TILE_PX,startX=Math.floor(parallaxX/chunkSize)-1,startY=Math.floor(parallaxY/chunkSize)-1,frames=[[0,0],[0,32],[32,0],[32,32]];for(let row=startY;row<startY+Math.ceil(canvas.height/chunkSize)+2;row++)for(let col=startX;col<startX+Math.ceil(canvas.width/chunkSize)+2;col++){const frame=frames[((row%frames.length)+frames.length)%frames.length],drawX=col*chunkSize-parallaxX,drawY=row*chunkSize-parallaxY;ctx.drawImage(backgroundTexture,frame[0],frame[1],32,32,drawX,drawY,chunkSize,chunkSize)}}
function drawSky(){const p=planets[save.planet],surfaceY=Math.max(0,Math.min(canvas.height,(SURFACE_Y-cameraY)*TILE_PX)),gradient=ctx.createLinearGradient(0,0,0,Math.max(1,surfaceY));gradient.addColorStop(0,p.skyTop);gradient.addColorStop(.55,p.base);gradient.addColorStop(1,p.skyBottom);ctx.fillStyle=gradient;ctx.fillRect(0,0,canvas.width,surfaceY);ctx.save();ctx.beginPath();ctx.rect(0,0,canvas.width,surfaceY);ctx.clip();for(let i=0;i<72;i++){const starX=((i*173-cameraX*TILE_PX*.035)%(canvas.width+24)+canvas.width+24)%(canvas.width+24)-12,starY=4+(i*47)%(Math.max(1,canvas.height-8)),size=i%11===0?2:1;ctx.fillStyle=i%7===0?'#d5efff':'#8ab8d8';ctx.fillRect(Math.round(starX),Math.round(starY),size,size)}ctx.restore()}
function draw(){const p=planets[save.planet];ctx.fillStyle=p.base;ctx.fillRect(0,0,canvas.width,canvas.height);const targetCameraX=state.visualX-viewCols/2,targetCameraY=Math.max(-viewRows/2,Math.min(H-viewRows,state.visualY-viewRows/2));if(!cameraReady){cameraX=targetCameraX;cameraY=targetCameraY;cameraReady=true}else{cameraX+=(targetCameraX-cameraX)*.18;cameraY+=(targetCameraY-cameraY)*.18}drawSky();drawBackground();drawForeground();const tileCameraX=Math.floor(cameraX),tileCameraY=Math.floor(cameraY),offsetX=Math.round((cameraX-tileCameraX)*TILE_PX),offsetY=Math.round((cameraY-tileCameraY)*TILE_PX);for(let sy=0;sy<viewRows+1;sy++)for(let sx=0;sx<viewCols+1;sx++){let x=sx+tileCameraX,y=sy+tileCameraY,c=tileAt(x,y);if(!c||c===PLATFORM_TILE||c===5)continue;let drawX=sx*TILE_PX-offsetX,drawY=sy*TILE_PX-offsetY,hit=tileHits.find(item=>item.x===wrapX(x)&&item.y===y),health=durability[y]?.[wrapX(x)]??3,lifeRatio=Math.max(0,Math.min(1,health/3));if(hit){const intensity=1-lifeRatio,progress=hit.elapsed/hit.duration,fade=1-progress,phase=hit.elapsed*.045,shake=(2+intensity*6)*fade;drawX+=Math.round(Math.sin(phase)*shake);drawY+=Math.round(Math.cos(phase*1.23)*shake)}if(tiles.complete){const [sourceX,sourceY]=c===4?[0,8]:terrainTexture(x,y);ctx.drawImage(tiles,sourceX,sourceY,ASSET_TILE,ASSET_TILE,drawX,drawY,TILE_PX,TILE_PX);if(c===3){ctx.fillStyle='rgba(221,91,67,.38)';ctx.fillRect(drawX,drawY,TILE_PX,TILE_PX)}}else{ctx.fillStyle=p.rock;ctx.fillRect(drawX,drawY,TILE_PX,TILE_PX)}if(hit?.flash){ctx.fillStyle='rgba(255,255,255,.95)';ctx.fillRect(drawX,drawY,TILE_PX,TILE_PX);hit.flash=false}}if(state.ended){ctx.fillStyle='rgba(10,12,14,.78)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#f2ead8';ctx.font='16px Press Start 2P';ctx.textAlign='center';ctx.fillText('MISSION DONE',canvas.width/2,Math.floor(canvas.height/2));ctx.fillStyle=p.accent;ctx.fillText('RETURN BASE',canvas.width/2,Math.floor(canvas.height/2)+32);ctx.textAlign='left'}}
function updateUI(){if(!state)return;const p=planets[save.planet];document.querySelector('#planet-name').textContent=p.name;document.querySelector('#planet-subtitle').textContent=p.sub;document.querySelector('#objective-text').textContent=p.objective;document.querySelector('#objective-count').textContent=Math.min(state.value,p.goal)+' / '+p.goal+'₡';document.querySelector('#objective-progress').style.width=Math.min(100,state.value/p.goal*100)+'%';document.querySelector('#depth-value').textContent=state.depth;document.querySelector('#run-value').textContent=state.value;document.querySelector('#combo-value').textContent=state.combo.toFixed(1);document.querySelector('#marker-depth').textContent=String(state.depth).padStart(3,'0')+'M';document.querySelector('#battery-label').textContent=Math.max(0,Math.round(state.battery))+'%';document.querySelector('#fuel-label').textContent=Math.max(0,Math.round(state.fuel))+'%';document.querySelector('#heat-label').textContent=Math.max(0,Math.round(state.heat))+'°';document.querySelector('#battery-bar').style.width=Math.max(0,state.battery)+'%';document.querySelector('#fuel-bar').style.width=Math.max(0,state.fuel)+'%';document.querySelector('#heat-bar').style.width=Math.min(100,state.heat)+'%';document.querySelector('#cargo-count').textContent=state.cargo.length;document.querySelector('#cargo-capacity').textContent=capacity();document.querySelector('#cargo-bar').style.width=state.cargo.length/capacity()*100+'%';document.querySelector('#event-text').textContent=state.event;document.querySelector('#credits-label').textContent=save.credits+'₡';document.querySelector('#best-score').textContent=save.best;document.querySelector('#session-score').textContent=state.value;document.querySelector('#planet-index').textContent=String(save.planet+1).padStart(2,'0');document.querySelector('#cargo-list').innerHTML=state.cargo.length?state.cargo.slice(-8).map(i=>`<span class="cargo-item" style="color:${i.color}">${i.name} +${i.value}₡</span>`).join(''):'<span class="empty-cargo">CARGO EMPTY</span>';document.querySelectorAll('.planet-dots i').forEach((el,i)=>el.classList.toggle('active',i===save.planet));renderUpgrades()}
function renderUpgrades(){const markup=upgrades.map(u=>{let level=upgradeLevel(u.id),cost=level<u.max?upgradeCost(u,level):Infinity;return `<div class="upgrade"><div class="upgrade-info">${u.name}<small>${u.desc} // LVL ${level}/${u.max}</small></div><button data-upgrade="${u.id}" ${level>=u.max||save.credits<cost?'disabled':''}>${level>=u.max?'MAX':cost+'₡'}</button></div>`}).join('');document.querySelector('#world-upgrade-list').innerHTML=markup;document.querySelector('#world-credits-label').textContent=save.credits+'₡'}
function updateFooter(){if(!state)return;const p=planets[save.planet],goal=p.goal,progress=Math.min(state.value,goal);document.querySelector('#footer-planet-index').textContent=String(save.planet+1).padStart(2,'0');document.querySelector('#footer-planet-name').textContent=p.name;document.querySelector('#footer-progress-bar').style.width=Math.min(100,state.value/goal*100)+'%';document.querySelector('#footer-credits').textContent=save.credits+'₡';document.querySelector('#footer-progress-value').textContent=progress+' / '+goal+'₡';document.querySelector('#footer-objective').textContent=p.objective}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Space'].includes(e.key)){e.preventDefault();keys[e.key]=true}if(e.key.toLowerCase()==='r')returnBase()});document.addEventListener('keyup',e=>{keys[e.key]=false});document.querySelector('#return-button').onclick=()=>returnBase();document.querySelectorAll('.mobile-controls button').forEach(btn=>{let k=btn.dataset.key;btn.addEventListener('pointerdown',()=>keys[k]=true);btn.addEventListener('pointerup',()=>keys[k]=false);btn.addEventListener('pointerleave',()=>keys[k]=false)});
function blocksLight(x,y){if(y<=SURFACE_Y)return false;const cell=tileAt(x,y);return cell>1&&cell!==PLATFORM_TILE&&cell!==5}
function shadowLevel(x,y){if(!blocksLight(x,y))return 0;for(let radius=1;radius<=5;radius++){for(let offset=-radius;offset<=radius;offset++){const candidates=[[x+offset,y-radius],[x+offset,y+radius],[x-radius,y+offset],[x+radius,y+offset]];if(candidates.some(([candidateX,candidateY])=>!blocksLight(candidateX,candidateY)))return Math.min(4,radius-1)}}return 5}
function drawShadows(){const tileCameraX=Math.floor(cameraX),tileCameraY=Math.floor(cameraY),offsetX=Math.round((cameraX-tileCameraX)*TILE_PX),offsetY=Math.round((cameraY-tileCameraY)*TILE_PX);for(let sy=0;sy<viewRows+1;sy++)for(let sx=0;sx<viewCols+1;sx++){const x=sx+tileCameraX,y=sy+tileCameraY,cell=terrain[y]?.[x],level=cell===PLATFORM_TILE?0:shadowLevel(x,y);if(!level||tileHits.some(hit=>hit.x===wrapX(x)&&hit.y===y))continue;const drawX=sx*TILE_PX-offsetX,drawY=sy*TILE_PX-offsetY;ctx.fillStyle=`rgba(8,10,11,${Math.min(1,level*.25)})`;ctx.fillRect(drawX,drawY,TILE_PX,TILE_PX)}}
function drawBorders(){const tileCameraX=Math.floor(cameraX),tileCameraY=Math.floor(cameraY),offsetX=Math.round((cameraX-tileCameraX)*TILE_PX),offsetY=Math.round((cameraY-tileCameraY)*TILE_PX),pixelScale=TILE_PX/ASSET_TILE;for(let sy=0;sy<viewRows+1;sy++)for(let sx=0;sx<viewCols+1;sx++){const x=sx+tileCameraX,y=sy+tileCameraY;if(terrain[y]?.[x]<=1||terrain[y]?.[x]===PLATFORM_TILE)continue;const drawX=sx*TILE_PX-offsetX,drawY=sy*TILE_PX-offsetY,edgeSize=pixelScale,edges=[!terrain[y-1]?.[x],!terrain[y]?.[x+1],!terrain[y+1]?.[x],!terrain[y]?.[x-1]];if(edges[0])ctx.drawImage(tiles,16,0,8,1,drawX,drawY,TILE_PX,edgeSize);if(edges[2])ctx.drawImage(tiles,16,9,8,1,drawX,drawY+TILE_PX-edgeSize,TILE_PX,edgeSize);if(edges[1]){ctx.save();ctx.translate(drawX+TILE_PX,drawY);ctx.rotate(Math.PI/2);ctx.drawImage(tiles,16,0,8,1,0,0,TILE_PX,edgeSize);ctx.restore()}if(edges[3]){ctx.save();ctx.translate(drawX,drawY+TILE_PX);ctx.rotate(-Math.PI/2);ctx.drawImage(tiles,16,0,8,1,0,0,TILE_PX,edgeSize);ctx.restore()}}}
function drawGeodeBases(){const tileCameraX=Math.floor(cameraX),tileCameraY=Math.floor(cameraY),offsetX=Math.round((cameraX-tileCameraX)*TILE_PX),offsetY=Math.round((cameraY-tileCameraY)*TILE_PX);for(let sy=0;sy<viewRows+1;sy++)for(let sx=0;sx<viewCols+1;sx++){const x=sx+tileCameraX,y=sy+tileCameraY;if(terrain[y]?.[x]!==4)continue;ctx.drawImage(tiles,0,8,ASSET_TILE,ASSET_TILE,sx*TILE_PX-offsetX,sy*TILE_PX-offsetY,TILE_PX,TILE_PX)}}
function drawChest(){const tileCameraX=Math.floor(cameraX),tileCameraY=Math.floor(cameraY),offsetX=Math.round((cameraX-tileCameraX)*TILE_PX),offsetY=Math.round((cameraY-tileCameraY)*TILE_PX),worldX=nearestWorldX(CHEST_X),drawX=(worldX-tileCameraX)*TILE_PX-offsetX,drawY=(CHEST_Y-tileCameraY)*TILE_PX-offsetY;if(tiles.complete)ctx.drawImage(tiles,0,16,ASSET_TILE,ASSET_TILE,drawX,drawY,TILE_PX,TILE_PX)}
function drawSurfaceRock(){const tileCameraX=Math.floor(cameraX),tileCameraY=Math.floor(cameraY),offsetX=Math.round((cameraX-tileCameraX)*TILE_PX),offsetY=Math.round((cameraY-tileCameraY)*TILE_PX);for(let sx=0;sx<viewCols+1;sx++){const x=sx+tileCameraX;if(tileAt(x,SURFACE_Y)!==5)continue;const drawX=sx*TILE_PX-offsetX,drawY=(SURFACE_Y-tileCameraY)*TILE_PX-offsetY;if(tiles.complete)ctx.drawImage(tiles,40,16,ASSET_TILE,ASSET_TILE,drawX,drawY,TILE_PX,TILE_PX)}}
function drawForeground(){if(!foregroundTexture.complete)return;const chunkSize=TILE_PX*4,parallaxX=.6,parallaxY=.18,offsetX=cameraX*parallaxX*TILE_PX,offsetY=cameraY*parallaxY*TILE_PX,startX=Math.floor(offsetX/chunkSize)-1,surfaceY=SURFACE_Y*TILE_PX-offsetY;for(let col=startX;col<startX+Math.ceil(canvas.width/chunkSize)+2;col++){const variant=Math.abs(col)%4,sourceX=(variant%2)*32,sourceY=Math.floor(variant/2)*32,drawX=col*chunkSize-offsetX;ctx.drawImage(foregroundTexture,sourceX,sourceY,32,32,drawX,surfaceY-chunkSize+TILE_PX,chunkSize,chunkSize)}}
function drawPlatforms(){const tileCameraX=Math.floor(cameraX),tileCameraY=Math.floor(cameraY),offsetX=Math.round((cameraX-tileCameraX)*TILE_PX),offsetY=Math.round((cameraY-tileCameraY)*TILE_PX);for(let sx=0;sx<viewCols+1;sx++){const x=sx+tileCameraX,wrappedX=wrapX(x);if(tileAt(x,SURFACE_Y)!==PLATFORM_TILE)continue;const drawX=sx*TILE_PX-offsetX,drawY=(SURFACE_Y-tileCameraY)*TILE_PX-offsetY,sourceX=wrappedX===ACCESS_START_X?16:wrappedX===ACCESS_START_X+ACCESS_WIDTH-1?32:24;if(tiles.complete)ctx.drawImage(tiles,sourceX,16,ASSET_TILE,ASSET_TILE,drawX,drawY,TILE_PX,TILE_PX)}}
function drawCharacterOverlay(){const px=(state.visualX-cameraX)*TILE_PX,py=(state.visualY-cameraY)*TILE_PX;ctx.fillStyle='rgba(0,0,0,.3)';ctx.fillRect(px+TILE_PX*.125,py+TILE_PX*.75,TILE_PX*.75,TILE_PX*.25);ctx.save();ctx.translate(px+TILE_PX/2,py+TILE_PX/2);ctx.rotate((state.rotation||0)*Math.PI/180);ctx.scale(state.facing||1,1);if(character.complete){const frame=characterFrame();ctx.drawImage(character,(frame%4)*8,Math.floor(frame/4)*8,8,8,-TILE_PX/2,-TILE_PX/2,TILE_PX,TILE_PX)}else{ctx.fillStyle='#d6d0b8';ctx.fillRect(-TILE_PX*.25,-TILE_PX/2,TILE_PX*.5,TILE_PX*.625);ctx.fillStyle='#5cdbcb';ctx.fillRect(-TILE_PX*.375,-TILE_PX*.125,TILE_PX*.75,TILE_PX*.375)}ctx.restore()}
function resizeViewport(){const pixelScale=Math.max(1,Math.floor(window.innerWidth/(VIEW_COLS*ASSET_TILE)));TILE_PX=ASSET_TILE*pixelScale;canvas.width=VIEW_COLS*TILE_PX;viewRows=Math.max(7,Math.floor(window.innerHeight/TILE_PX));canvas.height=viewRows*TILE_PX;viewCols=VIEW_COLS;ctx.imageSmoothingEnabled=false;ctx.imageSmoothingQuality='low';cameraReady=false}
window.addEventListener('resize',resizeViewport);resizeViewport();
function frame(t){let dt=Math.min(34,t-last||16);last=t;update(dt);updateFooter();draw();drawShadows();drawBorders();drawSurfaceRock();drawPlatforms();drawChest();drawWorkbench();drawCharacterOverlay();requestAnimationFrame(frame)}
document.addEventListener('pointerdown',()=>{if(spawnSoundPending)playSpawnSound()});document.addEventListener('keydown',()=>{if(spawnSoundPending)playSpawnSound()});loadSounds();newRun();requestAnimationFrame(frame);
